=== stoth68000/mpegts_ml/training/uc01-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Datetime and Video Stream Feature Schema",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "day_of_week": {
        "type": "integer",
        "minimum": 0,
        "maximum": 6
      },
      "hour": {
        "type": "integer",
        "minimum": 0,
        "maximum": 23
      },
      "minute": {
        "type": "integer",
        "minimum": 0,
        "maximum": 59
      },
      "second": {
        "type": "integer",
        "minimum": 0,
        "maximum": 59
      },
      "unixtime": {
        "type": "integer",
        "minimum": 0,
        "maximum": 4294967296
      },
      "avc_ibp_total_slice_count": {
        "type": "integer",
        "minimum": 0,
        "maximum": 500
      },
      "avc_ibp_total_slice_size": {
        "type": "integer",
        "minimum": 0,
        "maximum": 240000000
      },
      "transport_bit_count": {
        "type": "integer",
        "minimum": 0,
        "maximum": 240000000
      },
      "i_count": {
        "type": "integer",
        "minimum": 0,
        "maximum": 500
      },
      "p_count": {
        "type": "integer",
        "minimum": 0,
        "maximum": 500
      },
      "b_count": {
        "type": "integer",
        "minimum": 0,
        "maximum": 500
      },
      "on_air": {
        "type": "boolean"
      }
    },
    "required": [
      "day_of_week",
      "hour",
      "minute",
      "second",
      "unixtime",
      "avc_ibp_total_slice_count",
      "avc_ibp_total_slice_size",
      "transport_bit_count",
      "i_count",
      "b_count",
      "p_count",
      "on_air"
    ],
    "additionalProperties": false
  }
}

=== stoth68000/mpegts_ml/training/uc01-training.json
[
{ "day_of_week": 6, "hour": 8, "minute":  8, "second": 59, "unixtime": 1754741339, "avc_ibp_total_slice_count":  60, "avc_ibp_total_slice_size":    700728, "transport_bit_count":  19992672, "i_count":   1, "p_count":  14, "b_count":  45, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second":  0, "unixtime": 1754741340, "avc_ibp_total_slice_count":  60, "avc_ibp_total_slice_size":    700728, "transport_bit_count":  20024256, "i_count":   1, "p_count":  14, "b_count":  45, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second":  1, "unixtime": 1754741341, "avc_ibp_total_slice_count":  60, "avc_ibp_total_slice_size":    700728, "transport_bit_count":  19971616, "i_count":   1, "p_count":  14, "b_count":  45, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second":  2, "unixtime": 1754741342, "avc_ibp_total_slice_count":  59, "avc_ibp_total_slice_size":    700496, "transport_bit_count":  19761056, "i_count":   1, "p_count":  14, "b_count":  44, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second":  3, "unixtime": 1754741343, "avc_ibp_total_slice_count":  60, "avc_ibp_total_slice_size":    700728, "transport_bit_count":  20034784, "i_count":   1, "p_count":  14, "b_count":  45, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second":  4, "unixtime": 1754741344, "avc_ibp_total_slice_count":  60, "avc_ibp_total_slice_size":    700728, "transport_bit_count":  20076896, "i_count":   1, "p_count":  14, "b_count":  45, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second":  5, "unixtime": 1754741345, "avc_ibp_total_slice_count":  59, "avc_ibp_total_slice_size":    700496, "transport_bit_count":  19824224, "i_count":   1, "p_count":  14, "b_count":  44, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second":  6, "unixtime": 1754741346, "avc_ibp_total_slice_count":  61, "avc_ibp_total_slice_size":    700960, "transport_bit_count":  20161120, "i_count":   1, "p_count":  14, "b_count":  46, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second":  7, "unixtime": 1754741347, "avc_ibp_total_slice_count":  59, "avc_ibp_total_slice_size":    700496, "transport_bit_count":  19887392, "i_count":   1, "p_count":  14, "b_count":  44, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second":  8, "unixtime": 1754741348, "avc_ibp_total_slice_count":  61, "avc_ibp_total_slice_size":    700960, "transport_bit_count":  20076896, "i_count":   1, "p_count":  14, "b_count":  46, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second":  9, "unixtime": 1754741349, "avc_ibp_total_slice_count":  60, "avc_ibp_total_slice_size":    700728, "transport_bit_count":  20119008, "i_count":   1, "p_count":  14, "b_count":  45, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second": 10, "unixtime": 1754741350, "avc_ibp_total_slice_count":  60, "avc_ibp_total_slice_size":    700728, "transport_bit_count":  20045312, "i_count":   1, "p_count":  14, "b_count":  45, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second": 11, "unixtime": 1754741351, "avc_ibp_total_slice_count":  61, "avc_ibp_total_slice_size":    700960, "transport_bit_count":  20234816, "i_count":   1, "p_count":  14, "b_count":  46, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second": 12, "unixtime": 1754741352, "avc_ibp_total_slice_count":  59, "avc_ibp_total_slice_size":    700496, "transport_bit_count":  19792640, "i_count":   1, "p_count":  14, "b_count":  44, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second": 13, "unixtime": 1754741353, "avc_ibp_total_slice_count":  60, "avc_ibp_total_slice_size":    700728, "transport_bit_count":  20161120, "i_count":   1, "p_count":  14, "b_count":  45, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second": 14, "unixtime": 1754741354, "avc_ibp_total_slice_count":  59, "avc_ibp_total_slice_size":    700496, "transport_bit_count":  19603136, "i_count":   1, "p_count":  14, "b_count":  44, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second": 15, "unixtime": 1754741355, "avc_ibp_total_slice_count":  61, "avc_ibp_total_slice_size":    700960, "transport_bit_count":  20203232, "i_count":   1, "p_count":  14, "b_count":  46, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second": 16, "unixtime": 1754741356, "avc_ibp_total_slice_count":  59, "avc_ibp_total_slice_size":    700496, "transport_bit_count":  19750528, "i_count":   1, "p_count":  14, "b_count":  44, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second": 17, "unixtime": 1754741357, "avc_ibp_total_slice_count":  60, "avc_ibp_total_slice_size":    700728, "transport_bit_count":  20203232, "i_count":   1, "p_count":  14, "b_count":  45, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second": 18, "unixtime": 1754741358, "avc_ibp_total_slice_count":  60, "avc_ibp_total_slice_size":    700728, "transport_bit_count":  19866336, "i_count":   1, "p_count":  14, "b_count":  45, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second": 19, "unixtime": 1754741359, "avc_ibp_total_slice_count":  60, "avc_ibp_total_slice_size":    700728, "transport_bit_count":  19961088, "i_count":   1, "p_count":  14, "b_count":  45, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second": 20, "unixtime": 1754741360, "avc_ibp_total_slice_count":  61, "avc_ibp_total_slice_size":    700960, "transport_bit_count":  20340096, "i_count":   1, "p_count":  14, "b_count":  46, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second": 21, "unixtime": 1754741361, "avc_ibp_total_slice_count":  59, "avc_ibp_total_slice_size":    700496, "transport_bit_count":  19897920, "i_count":   1, "p_count":  14, "b_count":  44, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second": 22, "unixtime": 1754741362, "avc_ibp_total_slice_count":  61, "avc_ibp_total_slice_size":    700960, "transport_bit_count":  20161120, "i_count":   1, "p_count":  14, "b_count":  46, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second": 23, "unixtime": 1754741363, "avc_ibp_total_slice_count":  59, "avc_ibp_total_slice_size":    700496, "transport_bit_count":  19676832, "i_count":   1, "p_count":  14, "b_count":  44, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second": 24, "unixtime": 1754741364, "avc_ibp_total_slice_count":  59, "avc_ibp_total_slice_size":    700480, "transport_bit_count":  19929504, "i_count":   1, "p_count":  14, "b_count":  44, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second": 25, "unixtime": 1754741365, "avc_ibp_total_slice_count":  62, "avc_ibp_total_slice_size":    701208, "transport_bit_count":  20371680, "i_count":   1, "p_count":  14, "b_count":  47, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second": 26, "unixtime": 1754741366, "avc_ibp_total_slice_count":  59, "avc_ibp_total_slice_size":    700496, "transport_bit_count":  19929504, "i_count":   1, "p_count":  14, "b_count":  44, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second": 27, "unixtime": 1754741367, "avc_ibp_total_slice_count":  59, "avc_ibp_total_slice_size":    700480, "transport_bit_count":  19761056, "i_count":   1, "p_count":  14, "b_count":  44, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second": 28, "unixtime": 1754741368, "avc_ibp_total_slice_count":  60, "avc_ibp_total_slice_size":    700728, "transport_bit_count":  19918976, "i_count":   1, "p_count":  14, "b_count":  45, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second": 29, "unixtime": 1754741369, "avc_ibp_total_slice_count":  61, "avc_ibp_total_slice_size":    700976, "transport_bit_count":  20266400, "i_count":   1, "p_count":  14, "b_count":  46, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second": 30, "unixtime": 1754741370, "avc_ibp_total_slice_count":  60, "avc_ibp_total_slice_size":    700728, "transport_bit_count":  19940032, "i_count":   1, "p_count":  14, "b_count":  45, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second": 31, "unixtime": 1754741371, "avc_ibp_total_slice_count":  60, "avc_ibp_total_slice_size":    700728, "transport_bit_count":  20097952, "i_count":   1, "p_count":  14, "b_count":  45, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second": 32, "unixtime": 1754741372, "avc_ibp_total_slice_count":  59, "avc_ibp_total_slice_size":    700480, "transport_bit_count":  19666304, "i_count":   1, "p_count":  14, "b_count":  44, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second": 33, "unixtime": 1754741373, "avc_ibp_total_slice_count":  60, "avc_ibp_total_slice_size":    700728, "transport_bit_count":  19982144, "i_count":   1, "p_count":  14, "b_count":  45, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second": 34, "unixtime": 1754741374, "avc_ibp_total_slice_count":  61, "avc_ibp_total_slice_size":    700976, "transport_bit_count":  20308512, "i_count":   1, "p_count":  14, "b_count":  46, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second": 35, "unixtime": 1754741375, "avc_ibp_total_slice_count":  59, "avc_ibp_total_slice_size":    700480, "transport_bit_count":  19813696, "i_count":   1, "p_count":  14, "b_count":  44, "on_air": false },
{ "day_of_week": 6, "hour": 8, "minute":  9, "second": 36, "unixtime": 1754741376, "avc_ibp_total_slice_count":  60, "avc_ibp_total_slice_size":    700728, "transport_bit_count":  20182176, "i_count":   1, "p_count":  14, "b_count":  45, "on_air": false },
